name: Remove Files on PR

on:
  pull_request:
    branches:
      - "main"
      - "v99"

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      # - uses: actions/checkout@v2
      # git checkout ${GITHUB_BASE_REF} -- public
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git fetch
          git checkout [-f|--ours|--theirs|-m|--conflict=<style>] [<tree-ish>] [--] public
