name: Remove Files on PR

on:
  pull_request:
    branches:
      - "main"
      - "v99"

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      - uses: actions/checkout@v2
      - run: |
          git checkout main -- public
